### PR TITLE
DCM-19: Create six month april picker in run reports

### PR DESCRIPTION
**Pull request by Gravewalker666**
## Issue 
[[DCM - 19] Support Six-monthly April period type](https://issues.openmrs.org/browse/DCM-19)
The issue had two parts listed under it,
1. Update the backend
2. Update the date picker in the run reports 

The first part had already implemented with the issue DCM-32, so this PR contains the second part of the issue. 

## Approach 
* Created two html elements, an `input` for `sixMonthlyAprilPicker` and a `select` for `sixMonthAprilTypeSelector`
* Created a function to initialize the six monthly april picker
* Create a function to handle changes in the above html elements

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
@anjula-sack could you please have a look?

**Comment by HerbertYiga** [comment]
Thanks for working on this @Gravewalker666,  have you tested these changes in a running instance ?

**Comment by Gravewalker666** [comment]
@HerbertYiga Yes, I did test the UI in my local openmrs instance. Here's a screenshot of the UI
image

**Review by anjula-sack — APPROVED** [review]
Thank you! @Gravewalker666

**Review by jayasanka-sack — APPROVED** [review]
Thanks for getting this done, @Gravewalker666 !

sorry for taking some time to get this merged.

**Pull request merged**
