### PR TITLE
DCM-49: Add automated location mapping for Run Reports UI

### PR DESCRIPTION
**Pull request by Piumal1999**
## The issue I worked on
See [https://issues.openmrs.org/browse/DCM-49](https://issues.openmrs.org/browse/DCM-49) 

## Description of what I changed:
Upgraded the Run Reports Functionality to work with automated location mappings
Fixed a bug in location mapping UI

ezgif com-gif-maker (6)

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks cc @Piumal1999  don't for get to add tests for this!

**Comment by Piumal1999** [comment]
> thanks cc @Piumal1999 don't for get to add tests for this!

Hi @HerbertYiga 
Is it okay if I add Mockito (https://www.baeldung.com/injecting-mocks-in-spring) as an dependency for this in order to create the tests?

**Comment by HerbertYiga** [comment]
as long as the Mockito dependency doesn't not exist you can, have you tried to first use its classes before adding it?

**Comment by Piumal1999** [comment]
> as long as the Mockito dependency doesn't not exist you can, have you tried to first use its classes before adding it?

Yeah @HerbertYiga . No need to add the dependency. I used the classes.

Added the tests with bc50598

**Review by jayasanka-sack — APPROVED** [review]
Nicely done, @Piumal1999 ! This is more than expected!

**Pull request merged**
