### PR TITLE
DCM-6: Fix typos in the Mapping UI

### PR DESCRIPTION
**Pull request by Bawanthathilan**
# The issue I worked on

See https://issues.openmrs.org/browse/DCM-6
# Description of what I changed:
- Change `Mapped Category` to `Mapped Category Option Combination`
- Change `Data Element Options`  to `Data Elements`
- Change `Category Options`  to `Category Option Combinations`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@jayasanka-sack feel free to review this.

**Comment by jayasanka-sack** [comment]
Good job @Bawanthathilan ! Let's add a description for the PR to make it descriptive. 
Ex:
https://github.com/openmrs/openmrs-module-dhisconnector/pull/1

Rest of the things looks good to me! Thanks for contributing! 😊

**Review by jayasanka-sack — APPROVED** [review]
Thanks, Bawantha!

**Comment by dkayiwa** [comment]
@jayasanka-sack i have also given you admin access to the JIRA project. So feel free to manage the tickets. Can you ask the pull request authors to follow these? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

For instance, they should include a link to the pull request as a comment on the JIRA ticket.
And also take the ticket through the JIRA workflow before they ask you for review.

**Pull request merged**
