### PR TITLE
DCM-55: Add user privileges to Automation UI and Run Reports UI

### PR DESCRIPTION
**Pull request by Piumal1999**
## The issue I worked on
See [https://issues.openmrs.org/browse/DCM-55](https://issues.openmrs.org/browse/DCM-55) 

## Description of what I changed:
Updated the Automation UI and Run Reports UIs to behave according to the user privileges

## Related Thread and Preview:
https://talk.openmrs.org/t/dhis-connector-module-user-access-controlling/34059/8?u=piumal1999

### CODE REVIEW

**Comment by akshika47** [comment]
@jayasanka-sack would you be able to take a look at this PR?

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
@Piumal1999 Let me know once the conflicts are resolved

**Comment by Piumal1999** [comment]
> @Piumal1999 Let me know once the conflicts are resolved

Resolved the conflicts😊

**Review by jayasanka-sack — APPROVED** [review]
Perfect! thanks @Piumal1999 !

**Pull request merged**
