### PR TITLE
DCM-5: Hide the existing password from the UI

### PR DESCRIPTION
**Pull request by anjula-sack**
## The issue I worked on
See https://issues.openmrs.org/browse/DCM-5

## Description of what I changed:
Add the placeholder for the input
Remove the password value
Remove the password attribute from the backend

## Screenshot

image

### CODE REVIEW

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Good job @anjula-sack!

Let's remove the attribute from the backend too. 

`src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java`

**Comment by dkayiwa** [comment]
@jayasanka-sack i have just given you write access to this repository. So feel free to review and merge pull requests as you see best. 😊

**Comment by anjula-sack** [comment]
> Good job @anjula-sack!
> 
> Let's remove the attribute from the backend too.
> 
> `src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java`

sure

**Comment by jayasanka-sack** [comment]
> @jayasanka-sack i have just given you write access to this repository. So feel free to review and merge pull requests as you see best. 😊

Thanks @dkayiwa! 😇

**Review by jayasanka-sack — APPROVED** [review]
Good job! Thanks for contributing, Anjula!

**Comment by dkayiwa** [comment]
Same as i have commented on the other pull request. When one looks at the JIRA ticket, they can't tell why it is closed.

**Pull request merged**
